"""update most models

Revision ID: 72972f319e14
Revises: 
Create Date: 2024-12-31 13:29:34.764586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '72972f319e14'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('booking_user_id_fkey', 'booking', type_='foreignkey')
    op.drop_column('booking', 'user_id')
    op.add_column('driver', sa.Column('vehicle_registration_number', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False))
    op.drop_constraint('driver_vechile_registration_number_key', 'driver', type_='unique')
    op.create_unique_constraint(None, 'driver', ['vehicle_registration_number'])
    op.drop_column('driver', 'vechile_registration_number')
    op.drop_constraint('review_user_id_fkey', 'review', type_='foreignkey')
    op.drop_column('review', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key('review_user_id_fkey', 'review', 'user', ['user_id'], ['id'])
    op.add_column('driver', sa.Column('vechile_registration_number', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'driver', type_='unique')
    op.create_unique_constraint('driver_vechile_registration_number_key', 'driver', ['vechile_registration_number'])
    op.drop_column('driver', 'vehicle_registration_number')
    op.add_column('booking', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key('booking_user_id_fkey', 'booking', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
