"""Create the tables

Revision ID: c85d43f080c2
Revises: 
Create Date: 2025-03-28 01:56:33.656071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c85d43f080c2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('airport',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('airport_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('airport_location', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('iata_code', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('phone_number', sqlmodel.sql.sqltypes.AutoString(length=15), nullable=True),
    sa.Column('role', sa.Enum('tourist', 'driver', 'admin', 'staff', name='roleenum'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('languages_spoken', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('experience_years', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('service',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('vehicle_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('vehicle_registration_number', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('vehicle_model', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('vehicle_color', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('vehicle_capacity', sa.Integer(), nullable=False),
    sa.Column('available', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('airport_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['airport_id'], ['airport.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vehicle_registration_number')
    )
    op.create_table('booking',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('service_id', sa.Uuid(), nullable=False),
    sa.Column('number_of_passengers', sa.Integer(), nullable=False),
    sa.Column('booking_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['service.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('booking')
    op.drop_table('service')
    op.drop_table('user')
    op.drop_table('airport')
    # ### end Alembic commands ###
