"""Update table

Revision ID: e7f6912216b5
Revises: 96e497fde996
Create Date: 2025-03-27 23:59:51.776776

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e7f6912216b5'
down_revision: Union[str, None] = '96e497fde996'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'first_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('first_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
